displayName=Enhanced Messaging
author=Laurens Viaene
description=View private message conversations in the sidebar
tags=chat,private,messages,sidebar
version=
plugins=com.enhancedmessaging.EnhancedMessagingPlugin
build=standard
